name: Build & Deploy Spring app

on:
  push:
    branches:
      - main


jobs:
  build_deploy:
    name: Build and deploy spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4


      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Units Tests
        run: mvn -B test --file pom.xml


      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml 
